-- ==============================================
-- EXAM GUARDRAIL — SUPABASE SCHEMA
-- Run this in Supabase SQL Editor
-- ==============================================

-- DROP old tables (order matters due to foreign keys)
DROP TABLE IF EXISTS exam_tokens CASCADE;
DROP TABLE IF EXISTS credibility_reports CASCADE;
DROP TABLE IF EXISTS answer_scores CASCADE;
DROP TABLE IF EXISTS answers CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS exam_questions CASCADE;
DROP TABLE IF EXISTS exam_sessions CASCADE;
DROP TABLE IF EXISTS student_users CASCADE;
-- Also drop legacy tables from old schema
DROP TABLE IF EXISTS admin_users CASCADE;
DROP TABLE IF EXISTS exams CASCADE;
DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS behavioral_events CASCADE;

-- 1. STUDENT USERS (admin creates students, students login)
CREATE TABLE IF NOT EXISTS student_users (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  password TEXT NOT NULL,
  exam_name TEXT NOT NULL,
  is_eligible BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. EXAM SESSIONS (created on student login)
CREATE TABLE IF NOT EXISTS exam_sessions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  student_id TEXT NOT NULL,
  student_name TEXT,
  org_id TEXT,
  exam_name TEXT,
  subject_code TEXT,
  start_time TIMESTAMPTZ,
  end_time TIMESTAMPTZ,
  platform TEXT,
  device_type TEXT,
  credibility_score INTEGER DEFAULT 100,
  verdict TEXT DEFAULT 'CLEAR',
  status TEXT DEFAULT 'active',
  submitted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. EVENTS (L1-L4 telemetry from browser extension + native agent)
CREATE TABLE IF NOT EXISTS events (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  session_id UUID REFERENCES exam_sessions(id) ON DELETE CASCADE,
  layer TEXT DEFAULT 'L1',
  event_type TEXT NOT NULL,
  severity TEXT DEFAULT 'MEDIUM',
  payload JSONB DEFAULT '{}',
  alert_sentence TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. EXAM QUESTIONS (deployed by admin, AI-generated by Agent D)
CREATE TABLE IF NOT EXISTS exam_questions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  exam_name TEXT NOT NULL,
  subject_code TEXT,
  question_text TEXT NOT NULL,
  options JSONB NOT NULL,
  correct_answer TEXT,
  order_index INTEGER DEFAULT 0,
  start_time TIMESTAMPTZ,
  end_time TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. ANSWERS (student submissions)
CREATE TABLE IF NOT EXISTS answers (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  session_id UUID REFERENCES exam_sessions(id) ON DELETE CASCADE,
  question_id TEXT NOT NULL,
  answer_text TEXT NOT NULL,
  time_taken INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. ANSWER SCORES (Agent C AI-detection results)
CREATE TABLE IF NOT EXISTS answer_scores (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  session_id UUID REFERENCES exam_sessions(id) ON DELETE CASCADE,
  question_id TEXT NOT NULL,
  ai_probability FLOAT DEFAULT 0.0,
  verdict TEXT,
  flag_for_review BOOLEAN DEFAULT FALSE,
  signals_detected JSONB DEFAULT '[]',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. CREDIBILITY REPORTS (Agent B forensic reports)
CREATE TABLE IF NOT EXISTS credibility_reports (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  session_id UUID REFERENCES exam_sessions(id) ON DELETE CASCADE,
  student_id TEXT NOT NULL,
  student_name TEXT,
  exam_name TEXT,
  verdict TEXT,
  credibility_score INTEGER,
  executive_summary TEXT,
  policy_violations JSONB DEFAULT '[]',
  comparable_past_cases TEXT,
  recommendation TEXT,
  confidence FLOAT,
  generated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. EXAM TOKENS (prevents re-attendance, tracks completed exams per student)
CREATE TABLE IF NOT EXISTS exam_tokens (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  student_id TEXT NOT NULL,
  exam_name TEXT NOT NULL,
  subject_code TEXT,
  token TEXT UNIQUE NOT NULL,
  session_id UUID REFERENCES exam_sessions(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(student_id, exam_name)
);

-- ROW LEVEL SECURITY
ALTER TABLE student_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE exam_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE exam_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE answers ENABLE ROW LEVEL SECURITY;
ALTER TABLE answer_scores ENABLE ROW LEVEL SECURITY;
ALTER TABLE credibility_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE exam_tokens ENABLE ROW LEVEL SECURITY;

-- Allow all operations (use service role key for admin)
CREATE POLICY "allow_all" ON student_users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "allow_all" ON exam_sessions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "allow_all" ON events FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "allow_all" ON exam_questions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "allow_all" ON answers FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "allow_all" ON answer_scores FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "allow_all" ON credibility_reports FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "allow_all" ON exam_tokens FOR ALL USING (true) WITH CHECK (true);

-- REALTIME (for dashboard live monitoring)
ALTER PUBLICATION supabase_realtime ADD TABLE events;
ALTER PUBLICATION supabase_realtime ADD TABLE exam_sessions;
ALTER PUBLICATION supabase_realtime ADD TABLE credibility_reports;

-- INDEXES
CREATE INDEX IF NOT EXISTS idx_events_session ON events(session_id);
CREATE INDEX IF NOT EXISTS idx_events_session_layer ON events(session_id, layer);
CREATE INDEX IF NOT EXISTS idx_answers_session ON answers(session_id);
CREATE INDEX IF NOT EXISTS idx_scores_session ON answer_scores(session_id);
CREATE INDEX IF NOT EXISTS idx_student_users_uid ON student_users(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_status ON exam_sessions(status);
CREATE INDEX IF NOT EXISTS idx_tokens_student_exam ON exam_tokens(student_id, exam_name);

-- ==============================================
-- NATIVE DESKTOP AGENT TABLES
-- These use TEXT session_id (not UUID FK) so the
-- desktop app can use any exam code the admin provides.
-- ==============================================

-- 9. AGENT HEARTBEATS (one row per agent session, upserted every 5s)
DROP TABLE IF EXISTS agent_heartbeats CASCADE;
CREATE TABLE IF NOT EXISTS agent_heartbeats (
  id            UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  session_id    TEXT UNIQUE NOT NULL,          -- exam code, e.g. "ABC-123"
  platform      TEXT DEFAULT '',
  stats         JSONB DEFAULT '{}',
  last_seen     TIMESTAMPTZ DEFAULT NOW(),
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE agent_heartbeats ENABLE ROW LEVEL SECURITY;
CREATE POLICY "allow_all" ON agent_heartbeats FOR ALL USING (true) WITH CHECK (true);
ALTER PUBLICATION supabase_realtime ADD TABLE agent_heartbeats;
CREATE INDEX IF NOT EXISTS idx_heartbeats_session ON agent_heartbeats(session_id);
CREATE INDEX IF NOT EXISTS idx_heartbeats_last_seen ON agent_heartbeats(last_seen);

-- 10. NATIVE AGENT EVENTS (threats detected by desktop agent)
DROP TABLE IF EXISTS native_agent_events CASCADE;
CREATE TABLE IF NOT EXISTS native_agent_events (
  id            UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  session_id    TEXT NOT NULL,                 -- exam code (TEXT, not UUID FK)
  event_type    TEXT NOT NULL,
  severity      TEXT DEFAULT 'MEDIUM',
  layer         TEXT DEFAULT 'L4',
  score_delta   INTEGER DEFAULT -10,
  metadata      JSONB DEFAULT '{}',
  platform      TEXT DEFAULT '',
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE native_agent_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "allow_all" ON native_agent_events FOR ALL USING (true) WITH CHECK (true);
ALTER PUBLICATION supabase_realtime ADD TABLE native_agent_events;
CREATE INDEX IF NOT EXISTS idx_native_events_session ON native_agent_events(session_id);
CREATE INDEX IF NOT EXISTS idx_native_events_type ON native_agent_events(event_type);
CREATE INDEX IF NOT EXISTS idx_native_events_created ON native_agent_events(created_at DESC);

-- 11. AGENT CODES (short 6-char code → exam session UUID mapping)
DROP TABLE IF EXISTS agent_codes CASCADE;
CREATE TABLE IF NOT EXISTS agent_codes (
  id            UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  code          TEXT UNIQUE NOT NULL,              -- e.g. "A3X9K2"
  session_id    TEXT NOT NULL,                     -- exam session UUID (as text for flexibility)
  student_name  TEXT DEFAULT '',
  exam_name     TEXT DEFAULT '',
  admin_email   TEXT DEFAULT '',                   -- admin email for reports
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE agent_codes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "allow_all" ON agent_codes FOR ALL USING (true) WITH CHECK (true);
CREATE INDEX IF NOT EXISTS idx_agent_codes_code ON agent_codes(code);
CREATE INDEX IF NOT EXISTS idx_agent_codes_session ON agent_codes(session_id);

